### ISSUE TITLE
Множественная загрузка ресурсов.

### ISSUE THREAD

**Issue by 0da** [Bandarban/MyRunner#1]
https://github.com/Bandarban/MyRunner/blob/f0153f9796e9dbea43afdbd8b0c352515d7d5456/main.py#L192

https://github.com/Bandarban/MyRunner/blob/f0153f9796e9dbea43afdbd8b0c352515d7d5456/main.py#L206

При создании каждого объекта загружается новая картинка.  Наверно лучше будет если все объекты будут ссылаться на одно изображение. 

```python
...
tank = pygame.image.load('tank41.png')
	...
	self.image = tank
	self.image = tank
	...
```

**Comment by Bandarban** [comment]
Добавление спрайт-листа оставлено на потом. Это временный вариант.
